name: zema
description: "A high-performance, type-safe schema validation library for Dart & Flutter."
version: 0.2.0
homepage: https://github.com/meragix/zema
repository: https://github.com/meragix/zema
issue_tracker: https://github.com/meragix/zema/issues

environment:
  sdk: ">=3.5.0 <4.0.0"

resolution: workspace

dependencies:
  meta: ^1.18.1

dev_dependencies:
  test: ^1.24.0
  coverage: ^1.7.0
  benchmark_harness: ^2.2.0
  lints: ^6.1.0

topics:
  - validation
  - schema
  - parsing
  - zod
  - type-safe
