name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.9.0"
      
      - name: Cache pub
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: pub-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}

      - name: Install Melos
        run: dart pub global activate melos 7.4.0
      
      - name: Bootstrap
        run: melos bootstrap
      
      - name: Analyze
        run: melos analyze
      
      - name: Check formatting
        run: melos format:check

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: ["3.9.0", beta]
    steps:
      - uses: actions/checkout@v3
      
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      
      - name: Cache pub
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: pub-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}

      - name: Install Melos
        run: dart pub global activate melos 7.4.0
      
      - name: Bootstrap
        run: melos bootstrap
      
      - name: Run tests
        run: melos test
      
      - name: Upload coverage
        if: matrix.sdk == '3.9.0'
        uses: codecov/codecov-action@v3
        with:
          files: packages/zema/coverage/lcov.info
          fail_ci_if_error: fasle

  pana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.9.0"

      - name: Install tools
        run: |
          dart pub global activate melos 7.0.0
          dart pub global activate pana
      
      - name: Bootstrap
        run: melos bootstrap
      
      - name: Run Pana
        run: |
          cd packages/zema
          pana --exit-code-threshold 20